#include "adrena_core/sgsr1_pass.h"
#include "adrena_core/logger.h"
#include "embedded_shaders.h"          // auto-generated by embed_hlsl_shaders()
#include <d3dcompiler.h>

namespace adrena {

// ── MinGW-compatible barrier helper ──
struct ResourceBarrier : D3D12_RESOURCE_BARRIER {
    static ResourceBarrier Transition(ID3D12Resource* res,
        D3D12_RESOURCE_STATES before, D3D12_RESOURCE_STATES after,
        UINT sub = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES)
    {
        ResourceBarrier b{};
        b.Type                    = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
        b.Transition.pResource   = res;
        b.Transition.StateBefore = before;
        b.Transition.StateAfter  = after;
        b.Transition.Subresource = sub;
        return b;
    }
};

// ══════════════════════════════════════════════════════════════
//  Lifetime
// ══════════════════════════════════════════════════════════════

SGSR1Pass::~SGSR1Pass() { Shutdown(); }

bool SGSR1Pass::Init(ID3D12Device* device, DXGI_FORMAT fmt,
                     uint32_t rW, uint32_t rH, uint32_t dW, uint32_t dH)
{
    if (m_initialized) return true;
    if (!device) return false;

    m_device   = device;
    m_format   = fmt;
    m_renderW  = rW;
    m_renderH  = rH;
    m_displayW = dW;
    m_displayH = dH;

    if (!CreatePipeline())     return false;
    if (!CreateIntermediate()) return false;

    m_initialized = true;
    AD_LOG_I("SGSR1Pass initialized (official): %ux%u -> %ux%u fmt=%u",
             rW, rH, dW, dH, (uint32_t)fmt);
    return true;
}

void SGSR1Pass::Shutdown()
{
    if (m_pso)          { m_pso->Release();          m_pso = nullptr; }
    if (m_rootSig)      { m_rootSig->Release();      m_rootSig = nullptr; }
    if (m_srvHeap)      { m_srvHeap->Release();      m_srvHeap = nullptr; }
    if (m_samplerHeap)  { m_samplerHeap->Release();   m_samplerHeap = nullptr; }
    if (m_intermediate) { m_intermediate->Release();   m_intermediate = nullptr; }
    m_device      = nullptr;
    m_initialized = false;
    AD_LOG_I("SGSR1Pass shut down");
}

bool SGSR1Pass::Resize(uint32_t rW, uint32_t rH, uint32_t dW, uint32_t dH)
{
    m_renderW  = rW;  m_renderH  = rH;
    m_displayW = dW;  m_displayH = dH;

    if (m_intermediate) { m_intermediate->Release(); m_intermediate = nullptr; }
    if (m_srvHeap)      { m_srvHeap->Release();      m_srvHeap = nullptr; }

    return CreateIntermediate();
}

// ══════════════════════════════════════════════════════════════
//  Execute — main SGSR1 dispatch
// ══════════════════════════════════════════════════════════════

void SGSR1Pass::Execute(ID3D12GraphicsCommandList* cl, const SGSRParams& p)
{
    if (!m_initialized || !cl) return;
    if (!p.color || !p.output) return;

    // ── Determine current state of input ──
    D3D12_RESOURCE_DESC colorDesc = p.color->GetDesc();
    D3D12_RESOURCE_STATES colorBeforeState =
        (colorDesc.Flags & D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS)
            ? D3D12_RESOURCE_STATE_UNORDERED_ACCESS
            : D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE;

    // ── Transition input → SRV readable ──
    Transition(cl, p.color, colorBeforeState,
               D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);

    // ── Transition output → UAV writable ──
    Transition(cl, p.output, D3D12_RESOURCE_STATE_PRESENT,
               D3D12_RESOURCE_STATE_UNORDERED_ACCESS);

    // ── Create SRV for input color (heap slot 0 = t0) ──
    {
        D3D12_CPU_DESCRIPTOR_HANDLE h =
            m_srvHeap->GetCPUDescriptorHandleForHeapStart();

        D3D12_SHADER_RESOURCE_VIEW_DESC srvDesc{};
        srvDesc.Format                  = m_format;
        srvDesc.ViewDimension           = D3D12_SRV_DIMENSION_TEXTURE2D;
        srvDesc.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
        srvDesc.Texture2D.MipLevels     = 1;

        m_device->CreateShaderResourceView(p.color, &srvDesc, h);
    }

    // ── Create UAV for output (heap slot 1 = u0) ──
    {
        D3D12_CPU_DESCRIPTOR_HANDLE h =
            m_srvHeap->GetCPUDescriptorHandleForHeapStart();
        h.ptr += m_srvIncSize;

        D3D12_UNORDERED_ACCESS_VIEW_DESC uavDesc{};
        uavDesc.Format        = m_format;
        uavDesc.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;

        m_device->CreateUnorderedAccessView(p.output, nullptr, &uavDesc, h);
    }

    // ── Bind pipeline ──
    cl->SetComputeRootSignature(m_rootSig);
    cl->SetPipelineState(m_pso);

    ID3D12DescriptorHeap* heaps[] = { m_srvHeap, m_samplerHeap };
    cl->SetDescriptorHeaps(2, heaps);
    cl->SetComputeRootDescriptorTable(
        0, m_srvHeap->GetGPUDescriptorHandleForHeapStart());

    // ── Root constants (param index 2) ──
    //  Layout must match sgsr1_official.hlsl cbuffer exactly:
    //   [0]  renderW       uint32
    //   [1]  renderH       uint32
    //   [2]  displayW      uint32
    //   [3]  displayH      uint32
    //   [4]  sharpness     float
    //   [5]  frameCount    uint32
    //   [6]  edgeThreshold float
    //   [7]  operationMode uint32
    //   [8]  useEdgeDir    uint32
    //   [9]  padding0      float
    //  [10]  padding1      float   = 11 × 32 bits
    struct SGSR1Constants {
        uint32_t renderW;
        uint32_t renderH;
        uint32_t displayW;
        uint32_t displayH;
        float    sharpness;
        uint32_t frameCount;
        float    edgeThreshold;
        uint32_t operationMode;
        uint32_t useEdgeDir;
        float    padding0;
        float    padding1;
    };

    SGSR1Constants consts{};
    consts.renderW       = p.renderWidth;
    consts.renderH       = p.renderHeight;
    consts.displayW      = p.displayWidth;
    consts.displayH      = p.displayHeight;
    consts.sharpness     = p.sharpness;
    consts.frameCount    = 0;
    consts.edgeThreshold = p.edgeThreshold;
    consts.operationMode = static_cast<uint32_t>(p.operationMode);
    consts.useEdgeDir    = p.useEdgeDirection ? 1u : 0u;

    cl->SetComputeRoot32BitConstants(2, 11, &consts, 0);

    // ── Dispatch ──
    uint32_t dx = (m_displayW + 7) / 8;
    uint32_t dy = (m_displayH + 7) / 8;
    cl->Dispatch(dx, dy, 1);

    // ── UAV barrier — flush writes before transition ──
    {
        D3D12_RESOURCE_BARRIER uavBarrier{};
        uavBarrier.Type          = D3D12_RESOURCE_BARRIER_TYPE_UAV;
        uavBarrier.UAV.pResource = p.output;
        cl->ResourceBarrier(1, &uavBarrier);
    }

    // ── Transition output → PRESENT ──
    Transition(cl, p.output, D3D12_RESOURCE_STATE_UNORDERED_ACCESS,
               D3D12_RESOURCE_STATE_PRESENT);

    // ── Transition input → original state ──
    Transition(cl, p.color, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,
               colorBeforeState);
}

// ══════════════════════════════════════════════════════════════
//  Transition helper
// ══════════════════════════════════════════════════════════════

void SGSR1Pass::Transition(ID3D12GraphicsCommandList* cl, ID3D12Resource* res,
                           D3D12_RESOURCE_STATES before, D3D12_RESOURCE_STATES after)
{
    if (before == after) return;
    auto b = ResourceBarrier::Transition(res, before, after);
    cl->ResourceBarrier(1, &b);
}

// ══════════════════════════════════════════════════════════════
//  CreatePipeline — root signature + PSO
// ══════════════════════════════════════════════════════════════

bool SGSR1Pass::CreatePipeline()
{
    // ── Root signature layout ──
    //  [0] Descriptor table : SRV(t0) + UAV(u0)
    //  [1] Descriptor table : Sampler(s0) — empty, uses static sampler
    //  [2] Root constants   : 11 × uint32
    //  + 1 static sampler (s0, linear clamp)

    D3D12_ROOT_PARAMETER1 params[3]{};

    // ── Param 0: SRV + UAV table ──
    D3D12_DESCRIPTOR_RANGE1 ranges[2]{};

    ranges[0].RangeType                         = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
    ranges[0].NumDescriptors                    = 1;
    ranges[0].BaseShaderRegister                = 0;      // t0
    ranges[0].RegisterSpace                     = 0;
    ranges[0].Flags                             = D3D12_DESCRIPTOR_RANGE_FLAG_NONE;
    ranges[0].OffsetInDescriptorsFromTableStart = 0;

    ranges[1].RangeType                         = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
    ranges[1].NumDescriptors                    = 1;
    ranges[1].BaseShaderRegister                = 0;      // u0
    ranges[1].RegisterSpace                     = 0;
    ranges[1].Flags                             = D3D12_DESCRIPTOR_RANGE_FLAG_NONE;
    ranges[1].OffsetInDescriptorsFromTableStart = 1;

    params[0].ParameterType                       = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    params[0].DescriptorTable.NumDescriptorRanges = 2;
    params[0].DescriptorTable.pDescriptorRanges   = ranges;
    params[0].ShaderVisibility                    = D3D12_SHADER_VISIBILITY_ALL;

    // ── Param 1: Empty descriptor table for sampler heap binding ──
    params[1].ParameterType                       = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    params[1].DescriptorTable.NumDescriptorRanges = 0;
    params[1].DescriptorTable.pDescriptorRanges   = nullptr;
    params[1].ShaderVisibility                    = D3D12_SHADER_VISIBILITY_ALL;

    // ── Param 2: Root constants (11 × 32-bit) ──
    params[2].ParameterType            = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    params[2].Constants.ShaderRegister = 0;     // b0
    params[2].Constants.RegisterSpace  = 0;
    params[2].Constants.Num32BitValues = 11;
    params[2].ShaderVisibility         = D3D12_SHADER_VISIBILITY_ALL;

    // ── Static sampler ──
    D3D12_STATIC_SAMPLER_DESC staticSampler{};
    staticSampler.Filter           = D3D12_FILTER_MIN_MAG_MIP_LINEAR;
    staticSampler.AddressU         = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    staticSampler.AddressV         = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    staticSampler.AddressW         = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    staticSampler.ComparisonFunc   = D3D12_COMPARISON_FUNC_NEVER;
    staticSampler.ShaderRegister   = 0;         // s0
    staticSampler.RegisterSpace    = 0;
    staticSampler.ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

    // ── Serialize root signature ──
    D3D12_VERSIONED_ROOT_SIGNATURE_DESC rsDesc{};
    rsDesc.Version                    = D3D_ROOT_SIGNATURE_VERSION_1_1;
    rsDesc.Desc_1_1.NumParameters     = 3;
    rsDesc.Desc_1_1.pParameters       = params;
    rsDesc.Desc_1_1.NumStaticSamplers = 1;
    rsDesc.Desc_1_1.pStaticSamplers   = &staticSampler;
    rsDesc.Desc_1_1.Flags             = D3D12_ROOT_SIGNATURE_FLAG_NONE;

    ID3DBlob* sigBlob = nullptr;
    ID3DBlob* errBlob = nullptr;
    HRESULT hr = D3D12SerializeVersionedRootSignature(
        &rsDesc, &sigBlob, &errBlob);

    if (FAILED(hr)) {
        if (errBlob) {
            AD_LOG_E("SGSR1 RootSig serialize failed: %s",
                     (const char*)errBlob->GetBufferPointer());
            errBlob->Release();
        }
        return false;
    }

    hr = m_device->CreateRootSignature(
        0,
        sigBlob->GetBufferPointer(),
        sigBlob->GetBufferSize(),
        IID_PPV_ARGS(&m_rootSig));
    sigBlob->Release();

    if (FAILED(hr)) {
        AD_LOG_E("SGSR1 CreateRootSignature failed: 0x%08X", hr);
        return false;
    }

    // ═══════════════════════════════════════════════════════
    //  Compile compute shader from auto-embedded source
    // ═══════════════════════════════════════════════════════
    ID3DBlob* csBlob = nullptr;

    // shaders::sgsr1_official is generated by embed_hlsl_shaders()
    // from shaders/sgsr1_official.hlsl
    hr = D3DCompile(
        adrena::shaders::sgsr1_official,
        adrena::shaders::sgsr1_official_size,
        "sgsr1_official.hlsl",
        nullptr, nullptr,
        "CS_main", "cs_5_0",
        D3DCOMPILE_ENABLE_STRICTNESS, 0,
        &csBlob, &errBlob);

    if (FAILED(hr)) {
        AD_LOG_E("SGSR1 CS compile failed: %s",
                 errBlob ? (const char*)errBlob->GetBufferPointer()
                         : "unknown");
        if (csBlob)  csBlob->Release();
        if (errBlob) errBlob->Release();
        return false;
    }

    // ── Create PSO ──
    D3D12_COMPUTE_PIPELINE_STATE_DESC psoDesc{};
    psoDesc.pRootSignature = m_rootSig;
    psoDesc.CS             = { csBlob->GetBufferPointer(),
                               csBlob->GetBufferSize() };
    psoDesc.NodeMask       = 0;

    hr = m_device->CreateComputePipelineState(
        &psoDesc, IID_PPV_ARGS(&m_pso));
    csBlob->Release();

    if (FAILED(hr)) {
        AD_LOG_E("SGSR1 CreatePSO failed: 0x%08X", hr);
        return false;
    }

    AD_LOG_I("SGSR1Pass pipeline created");
    return true;
}

// ══════════════════════════════════════════════════════════════
//  CreateIntermediate — descriptor heaps + staging texture
// ══════════════════════════════════════════════════════════════

bool SGSR1Pass::CreateIntermediate()
{
    // ── CBV/SRV/UAV heap (2 descriptors: SRV t0 + UAV u0) ──
    D3D12_DESCRIPTOR_HEAP_DESC srvHeapDesc{};
    srvHeapDesc.Type           = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
    srvHeapDesc.NumDescriptors = 2;
    srvHeapDesc.Flags          = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
    srvHeapDesc.NodeMask       = 0;

    HRESULT hr = m_device->CreateDescriptorHeap(
        &srvHeapDesc, IID_PPV_ARGS(&m_srvHeap));
    if (FAILED(hr)) {
        AD_LOG_E("SGSR1 CreateDescriptorHeap(SRV/UAV) failed: 0x%08X", hr);
        return false;
    }

    m_srvIncSize = m_device->GetDescriptorHandleIncrementSize(
        D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);

    // ── Sampler heap (1 descriptor) ──
    D3D12_DESCRIPTOR_HEAP_DESC sampHeapDesc{};
    sampHeapDesc.Type           = D3D12_DESCRIPTOR_HEAP_TYPE_SAMPLER;
    sampHeapDesc.NumDescriptors = 1;
    sampHeapDesc.Flags          = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
    sampHeapDesc.NodeMask       = 0;

    hr = m_device->CreateDescriptorHeap(
        &sampHeapDesc, IID_PPV_ARGS(&m_samplerHeap));
    if (FAILED(hr)) {
        AD_LOG_E("SGSR1 CreateDescriptorHeap(Sampler) failed: 0x%08X", hr);
        return false;
    }

    // Write sampler descriptor (linear clamp)
    D3D12_SAMPLER_DESC samplerDesc{};
    samplerDesc.Filter         = D3D12_FILTER_MIN_MAG_MIP_LINEAR;
    samplerDesc.AddressU       = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    samplerDesc.AddressV       = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    samplerDesc.AddressW       = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    samplerDesc.ComparisonFunc = D3D12_COMPARISON_FUNC_NEVER;
    samplerDesc.MinLOD         = 0.0f;
    samplerDesc.MaxLOD         = D3D12_FLOAT32_MAX;

    m_device->CreateSampler(
        &samplerDesc,
        m_samplerHeap->GetCPUDescriptorHandleForHeapStart());

    // ── Intermediate staging texture (render-resolution, UAV-capable) ──
    D3D12_RESOURCE_DESC texDesc{};
    texDesc.Dimension          = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
    texDesc.Width              = m_renderW;
    texDesc.Height             = m_renderH;
    texDesc.DepthOrArraySize   = 1;
    texDesc.MipLevels          = 1;
    texDesc.Format             = m_format;
    texDesc.SampleDesc.Count   = 1;
    texDesc.SampleDesc.Quality = 0;
    texDesc.Layout             = D3D12_TEXTURE_LAYOUT_UNKNOWN;
    texDesc.Flags              = D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;

    D3D12_HEAP_PROPERTIES defaultHeap{};
    defaultHeap.Type = D3D12_HEAP_TYPE_DEFAULT;

    D3D12_CLEAR_VALUE clearVal{};
    clearVal.Format = m_format;
    memset(clearVal.Color, 0, sizeof(clearVal.Color));

    hr = m_device->CreateCommittedResource(
        &defaultHeap,
        D3D12_HEAP_FLAG_NONE,
        &texDesc,
        D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,
        &clearVal,
        IID_PPV_ARGS(&m_intermediate));

    if (FAILED(hr)) {
        AD_LOG_E("SGSR1 CreateIntermediate resource failed: 0x%08X", hr);
        return false;
    }

    AD_LOG_I("SGSR1Pass intermediate created (%ux%u)", m_renderW, m_renderH);
    return true;
}

} // namespace adrena
